defaults:
  data_source: &flash_ansr_fastsrb_source
    type: fastsrb
    benchmark_path: "{{ROOT}}/data/ansr-data/test_set/fastsrb/expressions.yaml"
    datasets_per_expression: 10
    support_points: 512
    sample_points: 1024
    method: random
    max_trials: 100
    incremental: false
    random_state: 42
    noise_level: 0.0
  model_adapter: &flash_ansr_adapter
    type: flash_ansr
    model_path: "{{ROOT}}/models/ansr-models/v23.0-120M"
    evaluation_config:
      n_support: 512
      n_restarts: 8
      refiner_method: curve_fit_lm
      refiner_p0_noise: normal
      refiner_p0_noise_kwargs:
        loc: 0.0
        scale: 5
      length_penalty: 0.05
      constants_penalty: 0.0
      likelihood_penalty: 0.0
      prune_constant_budget: 0
      generation_config:
        method: beam_search
        kwargs:
          beam_width: 32
          max_len: 128
          batch_size: 128
          unique: true
      device: cuda
    complexity: none
    device: cuda
  runner: &flash_ansr_fastsrb_runner
    limit: null
    save_every: 64
    resume: true

experiments:
  flash_ansr_fastsrb_beam_search_00001:
    run:
      data_source: *flash_ansr_fastsrb_source
      model_adapter:
        <<: *flash_ansr_adapter
        generation_overrides:
          kwargs:
            beam_width: 1
      runner:
        <<: *flash_ansr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/v23.0-120M-Z2-beam/fastsrb/beam_search_00001.pkl"

  flash_ansr_fastsrb_beam_search_00004:
    run:
      data_source: *flash_ansr_fastsrb_source
      model_adapter:
        <<: *flash_ansr_adapter
        generation_overrides:
          kwargs:
            beam_width: 4
      runner:
        <<: *flash_ansr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/v23.0-120M-Z2-beam/fastsrb/beam_search_00004.pkl"

  flash_ansr_fastsrb_beam_search_00016:
    run:
      data_source: *flash_ansr_fastsrb_source
      model_adapter:
        <<: *flash_ansr_adapter
        generation_overrides:
          kwargs:
            beam_width: 16
      runner:
        <<: *flash_ansr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/v23.0-120M-Z2-beam/fastsrb/beam_search_00016.pkl"

  flash_ansr_fastsrb_beam_search_00064:
    run:
      data_source: *flash_ansr_fastsrb_source
      model_adapter:
        <<: *flash_ansr_adapter
        generation_overrides:
          kwargs:
            beam_width: 64
      runner:
        <<: *flash_ansr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/v23.0-120M-Z2-beam/fastsrb/beam_search_00064.pkl"

  flash_ansr_fastsrb_beam_search_00256:
    run:
      data_source: *flash_ansr_fastsrb_source
      model_adapter:
        <<: *flash_ansr_adapter
        generation_overrides:
          kwargs:
            beam_width: 256
      runner:
        <<: *flash_ansr_fastsrb_runner
        output: "{{ROOT}}/results/evaluation/scaling/v23.0-120M-Z2-beam/fastsrb/beam_search_00256.pkl"
