"""Whole-suite config for an out-of-process baseline (srbf `type: subprocess`): one experiment per srbf
catalog, the method's compute axis as a `ladder` sweep, one draw per expression per pass (another pass
under another FLASH_ANSR_ROOT is another draw). Mirrors srbf's scripts/make_scaling_configs.py.
usage: make_baseline_config.py diffsym <python> <model_path> <config_dir> <out.yaml> [ladder]"""
import sys
from srbf.suites import SRBF_CATALOGS
method = sys.argv[1]
if method == "diffsym":
    python, model_path, config_dir, out = sys.argv[2:6]
    ladder = [int(v) for v in sys.argv[6].split(",")] if len(sys.argv) > 6 else [1, 2, 4, 8, 16, 32, 64, 128]
elif method == "nesymres":
    # usage: make_baseline_config.py nesymres <models_dir with eq_setting.json, config.yaml, 100M.ckpt> <out.yaml> [ladder]
    models_dir, out = sys.argv[2:4]
    ladder = [int(v) for v in sys.argv[4].split(",")] if len(sys.argv) > 4 else [1, 2, 4, 8, 16, 32, 128, 512]
elif method == "e2e":
    # usage: make_baseline_config.py e2e <model1.pt> <out.yaml> [ladder]; max_generated_output_len follows the campaign schedule
    model_path, out = sys.argv[2:4]
    # E2E at its DEFAULT settings only (owner 2026-09-16): no decoder-length schedule, and the ladder ends at the largest
    # rung that runs at those defaults on the reference GPU (RTX 4090; 256 verified, larger rungs only after a memory probe)
    ladder = [int(v) for v in sys.argv[4].split(",")] if len(sys.argv) > 4 else [1, 2, 4, 8, 16, 32, 64, 128, 256]
    E2E_MAX_LEN = 200   # E2E's default max_generated_output_len, at every rung
else:
    raise SystemExit("method must be diffsym, nesymres or e2e")
name = {"diffsym": "diffsym-v4.0", "nesymres": "nesymres-100M", "e2e": "e2e"}[method]
AXIS = {"diffsym": "n_samples", "nesymres": "beam_width", "e2e": "candidates_per_bag"}[method]

def adapter_block():
    if method == "diffsym":
        return f"""      config_provenance: upstream_default
      type: subprocess
      worker: diffsym
      python: {python}
      simplipy_engine: acj-5-4-llm
      timeout: 3600
      startup_timeout: 900
      options:
        model_path: {model_path}
        config_dir: {config_dir}
        n_samples: !sweep {{name: ladder, values: {ladder}}}
        seq_len: 100
        n_restarts: 8
        method: curve_fit_lm
        simplipy_engine: dev_7-3"""
    if method == "nesymres":
        return f"""      config_provenance: upstream_default
      type: nesymres
      eq_setting_path: {models_dir}/eq_setting.json
      config_path: {models_dir}/config.yaml
      weights_path: {models_dir}/100M.ckpt
      simplipy_engine: acj-5-4-llm
      n_restarts: 4
      device: cuda
      remove_padding: true
      beam_width: !sweep {{name: ladder, values: {ladder}}}"""
    return f"""      config_provenance: upstream_default
      type: e2e
      model_path: {model_path}
      simplipy_engine: acj-5-4-llm
      device: cuda
      candidates_per_bag: !sweep {{name: ladder, values: {ladder}}}
      max_input_points: 200
      max_number_bags: 100
      n_trees_to_refine: 10
      max_generated_output_len: {E2E_MAX_LEN}
      rescale: true"""

def experiment(catalog):
    outs = ", ".join(f"'{{{{ROOT}}}}/results/evaluation/scaling/{name}/{catalog}/choices_{c:06d}.pkl'" for c in ladder)
    return f"""
  {catalog}:
    data_source:
      catalog: {catalog}
      sampling: {{n_support: 512, n_validation: 512, noise: 0.0, problems_per_expression: 1}}
    model_adapter:
{adapter_block()}
    runner:
      limit: null
      save_every: 8
      resume: true
      output: !sweep
        name: ladder
        values: [{outs}]
"""
HEADS = {
 "diffsym": "# diffsym v4.0 (Mara Eliana; D3PM discrete diffusion, 119M, 8 variables) on every srbf catalog: recovery as a\n# function of its sampling budget n_samples (its default is 100). Out of process in diffsym's own interpreter\n# (simplipy 0.2.15 pinned; decodes with dev_7-3, srbf judges with acj-5-4-llm).",
 "nesymres": "# NeSymReS 100M (Biggio et al. 2021; clone 92d7c46 patched per srbf docs/models.md) on every srbf catalog:\n# recovery as a function of its beam width (upstream default 4). In-process adapter (type: nesymres).",
 "e2e": "# E2E / symbolicregression (Kamienny et al. 2022; clone c4144c9 patched per srbf docs/models.md) on every srbf\n# catalog: recovery as a function of candidates_per_bag (default settings: max_generated_output_len 200 at every rung).\n# In-process adapter (type: e2e).",
}
head = (HEADS[method] + "\n# One experiment per catalog (`--experiment <catalog>`), one rung per budget (`--sweep-filter ladder=<n>`), one draw per\n# expression per pass. Generated by make_baseline_config.py; do not edit by hand.\nexperiments:\n")
_unused = ("# diffsym v4.0 (Mara Eliana; D3PM discrete diffusion, 119M, 8 variables) on every srbf catalog: recovery as a\n"
        "# function of its sampling budget n_samples 1..128 (its default is 100). Out of process in diffsym's own\n"
        "# interpreter (simplipy 0.2.15 pinned; decodes with dev_7-3, srbf judges with acj-5-4-llm). One experiment per\n"
        "# catalog (`--experiment <catalog>`), one rung per n_samples (`--sweep-filter ladder=<n>`), one draw per\n"
        "# expression per pass. Generated by make_baseline_config.py; do not edit by hand.\nexperiments:\n")
open(out, "w").write(head + "".join(experiment(c) for c in SRBF_CATALOGS).lstrip("\n"))
print(out, len(SRBF_CATALOGS), "experiments x", len(ladder), "rungs")
