"""Generate the whole-suite inference-scaling configs for the flash-ansr reference checkpoints.

One config per checkpoint, one experiment per srbf catalog, the 1..16,384 ladder in every
experiment, ONE draw per expression per pass: a pass on another host under its own
FLASH_ANSR_ROOT is another draw, and the passes are joined by problem id afterwards.

    python scripts/make_scaling_configs.py        # rewrites configs/evaluation/scaling/*_srbf.yaml
"""
from __future__ import annotations

import pathlib

from srbf.suites import SRBF_CATALOGS

CATALOGS = list(SRBF_CATALOGS)
LADDER = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]
MODELS = {
    'flash-ansr-v25.0-T7-3M': 'psaegert/flash-ansr-v25.0-T7-3M',
    'flash-ansr-v25.0-T7-20M': 'psaegert/flash-ansr-v25.0-T7-20M',
}
ROOT = pathlib.Path(__file__).resolve().parents[1]


def experiment(model: str, repo: str, catalog: str) -> str:
    outs = ', '.join(
        f"'{{{{ROOT}}}}/results/evaluation/scaling/{model}/{catalog}/choices_{c:06d}.pkl'" for c in LADDER)
    return f"""
  {catalog}:
    data_source:
      catalog: {catalog}
      sampling:
        n_support: 512
        n_validation: 512
        noise: 0.0
        problems_per_expression: 1
    model_adapter:
      config_provenance: author_blessed
      type: flash_ansr
      model_path: '{{{{ROOT}}}}/models/{repo}'
      emission: fittable
      refine_scope: fittable
      complexity: none
      device: cuda
      evaluation_config:
        n_support: 512
        n_restarts: 8
        refiner_method: curve_fit_lm
        refiner_p0_noise: normal
        refiner_p0_noise_kwargs:
          loc: 0.0
          scale: 5
        ranking:
          mode: mdl
          mdl_strength: 1.0e-2
        prune_constant_budget: 0
        generation_config:
          method: softmax_sampling
          kwargs:
            choices: 1024
            top_k: 0
            top_p: 1
            max_len: 160
            batch_size: 128
            temperature: 1
            valid_only: true
            simplify: true
            unique: true
        device: cuda
      generation_overrides:
        kwargs:
          choices: !sweep
            name: ladder
            values: {LADDER}
    runner:
      limit: null
      save_every: 64
      resume: true
      output: !sweep
        name: ladder
        values: [{outs}]
"""


def main() -> None:
    for model, repo in MODELS.items():
        head = (f"# {repo} on every srbf catalog: recovery as a function of the sampling budget, 1 to 16,384\n"
                f"# choices. One experiment per catalog (`--experiment <catalog>`), one rung per candidate count\n"
                f"# (`--sweep-filter ladder=<choices>`), ONE draw per expression per pass; run the config again under\n"
                f"# another FLASH_ANSR_ROOT for another draw. The model directory is where `flash_ansr install` puts\n"
                f"# the checkpoint. Generated by scripts/make_scaling_configs.py; do not edit by hand.\n"
                f"experiments:\n")
        body = ''.join(experiment(model, repo, c) for c in CATALOGS)
        path = ROOT / 'configs' / 'evaluation' / 'scaling' / f'{model}_srbf.yaml'
        path.write_text(head + body.lstrip('\n'))
        print(path.relative_to(ROOT), len(CATALOGS), 'experiments x', len(LADDER), 'rungs')


if __name__ == '__main__':
    main()
